### ISSUE TITLE
Can't install in LibreOffice: No module named 'dateutil' (or 'dateutil.tz' is unknown)

### ISSUE THREAD

**Issue by Johann-Tree** [prometheus42/libreoffice-ical-importer#1]
I'm using Ubuntu 20.04.5 LTS and LibreOffice 7.3.2.2 .
I cloned the repo, installed Ics.py via
`pip install ics`
, changed into the directory and then built the extension with
./build.py
When trying to install the extension in LibreOffice, I got following error:
![ErrorMessage_when_installing_in_LibreOffice](https://user-images.githubusercontent.com/3155020/204736308-7b5e527f-a9b9-42a5-8af5-9e8cbbb311a4.png)

Checking dateutil again:
`pip install python-dateutil`
returns

> Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (2.7.3)

**Comment by prometheus42** [comment]
Sorry for answering late, but I had no free time until now.

The file `build.py` was my first attempt for building the extension based on some examples I found online. For the release 0.1 I used the Makefile in the repository. I just clarified the build instructions in the README file.

If you install all dependencies with `pip install ics arrow` and follow the instructions it should work.
