### ISSUE TITLE
Can we launch from the command line with an argument

### ISSUE THREAD

**Issue by ventoux84** [prometheus42/libreoffice-ical-importer#4]
Hello,
Is it possible to launch import_ical.py in command line with the path to the file to import as argument ?
Tanks

**Comment by wichmann** [comment]
Sadly that is currently not possible. The LibreOffice extension `import_ical.py` has no command line interface. If you need to use the CLI you could use `ical2csv.py`, which provides one. Just type `./ical2csv.py --help` for more information.

**Comment by prometheus42** [comment]
Sadly that is currently not possible. The LibreOffice extension `import_ical.py` has no command line interface. If you need to use the CLI you could use `ical2csv.py`, which provides one. Just type `./ical2csv.py --help` for more information.

**Comment by ventoux84** [comment]
It's about the cell "Duration". I use it in Calc and i may do in another cell "=CNUM(duration)"

**Comment by ventoux84** [comment]
Thanks for the that.
