### ISSUE TITLE
use your extension libreoffice-ical-importer in libre calc?

### ISSUE THREAD

**Issue by pe4000** [prometheus42/libreoffice-ical-importer#6]
Dear Mr. Wichmann,
How can I use your extension libreoffice-ical-importer in libre calc?
Kind regards
Peter

**Comment by wichmann** [comment]
1. Download LibreOffice extension: https://github.com/prometheus42/libreoffice-ical-importer/releases/tag/v0.2
2. Install extension in LibreOffice
3. Open LibreOffice Calc
4. Click on the tools ("Werkzeuge") menu and start the import function
5. Choose iCal file

The fields of the iCal file should be stored as columns in the table.

**Comment by prometheus42** [comment]
1. Download LibreOffice extension: https://github.com/prometheus42/libreoffice-ical-importer/releases/tag/v0.2
2. Install extension in LibreOffice
3. Open LibreOffice Calc
4. Click on the tools ("Werkzeuge") menu and start the import function
5. Choose iCal file

The fields of the iCal file should be stored as columns in the table.

**Comment by RayCulp** [comment]
@pe4000 Don't forget to install the [dependencies](https://github.com/prometheus42/libreoffice-ical-importer?tab=readme-ov-file#requirements) also, otherwise it won't work.
