### ISSUE TITLE
Import fails if iCalendar file name has spaces

### ISSUE THREAD

**Issue by RayCulp** [prometheus42/libreoffice-ical-importer#7]
## Description:
If the name of the *.ics file to be imported contains spaces, the import fails silently. The column headers are written to the Calc file, but no events.

![image](https://github.com/prometheus42/libreoffice-ical-importer/assets/7621330/6663bcb2-556d-4990-9337-53ed33cff786)

## Steps to reproduce

1. Export an *.ics file from a calendar application without spaces in the file name
2. Confirm that this *.ics file can be correctly imported into a Calc file using iCalendar Importer extension.
3. Rename the *.ics file to include spaces in file name.
4. Attempt to import the file name with spaces.

## Expected Result:
iCalendar Importer extension should import the *.ics file into Calc.

## Actual Result:
Import fails silently. Column headers are written to Calc file, but no events are imported.

## Error Message:
None

## Operating System
OS: Ubuntu 22.04 LTS

## Software
Program: LibreOffice
Version: 24.2

## Additional Information
None

**Comment by RayCulp** [comment]
The error is occurring here because the LibreOffice file picker dialog escapes spaces with %20, but the Python open command appears to be interpreting %20 literally.

![image](https://github.com/prometheus42/libreoffice-ical-importer/assets/7621330/dc790c64-0757-4049-be27-5020abaa23f5)

**Comment by RayCulp** [comment]
I can confirm that this can be fixed by adding `.replace('%20', ' ')` at the end of this statement.

![image](https://github.com/prometheus42/libreoffice-ical-importer/assets/7621330/aefa52ec-3b6d-4145-a13c-0ea1b8ee2e25)

**Comment by prometheus42** [comment]
Fixed with 1688dfef2d2cfbaf85dfe19c5b68ddc523f778c6.
